"""Mako template for migration scripts."""

"""add installer params to service models

Revision ID: c8f694417467
Revises: a38f0cdc7e8c
Create Date: 2026-04-26 10:55:04.041013

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c8f694417467'
down_revision = 'a38f0cdc7e8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('awg_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('subnet_ip', sa.String(length=50), nullable=False, server_default="10.8.0.1"))
        batch_op.add_column(sa.Column('subnet_cidr', sa.Integer(), nullable=False, server_default="24"))
        batch_op.add_column(sa.Column('obfuscation', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('server_public_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('server_private_key', sa.String(length=100), nullable=True))

    with op.batch_alter_table('mtproxy_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('implementation', sa.String(length=20), nullable=False, server_default="mtg-multi"))
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=False, server_default="443"))
        batch_op.add_column(sa.Column('domain', sa.String(length=200), nullable=False, server_default="google.com"))
        batch_op.add_column(sa.Column('max_connections', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_secret', sa.String(length=200), nullable=True))

    with op.batch_alter_table('xui_panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caddy_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inbound_ranges', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xui_panels', schema=None) as batch_op:
        batch_op.drop_column('inbound_ranges')
        batch_op.drop_column('caddy_port')

    with op.batch_alter_table('mtproxy_services', schema=None) as batch_op:
        batch_op.drop_column('default_secret')
        batch_op.drop_column('max_connections')
        batch_op.drop_column('domain')
        batch_op.drop_column('port')
        batch_op.drop_column('implementation')

    with op.batch_alter_table('awg_services', schema=None) as batch_op:
        batch_op.drop_column('server_private_key')
        batch_op.drop_column('server_public_key')
        batch_op.drop_column('obfuscation')
        batch_op.drop_column('subnet_cidr')
        batch_op.drop_column('subnet_ip')
        batch_op.drop_column('port')

    # ### end Alembic commands ###
