"""Mako template for migration scripts."""

"""add domain to mtproxy connections

Revision ID: cc6484af2b44
Revises: c8f694417467
Create Date: 2026-04-29 11:00:43.463544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6484af2b44'
down_revision = 'c8f694417467'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mtproxy_inbound_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mtproxy_inbound_connections', schema=None) as batch_op:
        batch_op.drop_column('domain')

    # ### end Alembic commands ###
