"""Mako template for migration scripts."""

"""normalize_db_architecture

Revision ID: 6ef042042a42
Revises: f61af02614a9
Create Date: 2026-04-24 19:50:45.336083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "6ef042042a42"
down_revision = "f61af02614a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "awg_services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id"),
    )
    op.create_table(
        "mtproxy_services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id"),
    )
    op.create_table(
        "xui_panels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("password_encrypted", sa.Text(), nullable=True),
        sa.Column("verify_ssl", sa.Boolean(), nullable=False),
        sa.Column("panel_type", sa.String(length=50), nullable=True),
        sa.Column("provider_payload", sa.JSON(), nullable=True),
        sa.Column("panel_path", sa.String(length=500), nullable=True),
        sa.Column("subscription_path", sa.String(length=500), nullable=True),
        sa.Column("subscription_json_path", sa.String(length=500), nullable=True),
        sa.Column("session_cookies_encrypted", sa.Text(), nullable=True),
        sa.Column("session_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id"),
    )
    op.create_table(
        "awg_inbounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["inbounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mtproxy_inbounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["inbounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "xui_inbounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("xui_id", sa.Integer(), nullable=False),
        sa.Column("settings_json", sa.Text(), nullable=True),
        sa.Column("provider_payload", sa.JSON(), nullable=True),
        sa.Column("client_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["inbounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "awg_inbound_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["inbound_connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mtproxy_inbound_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["inbound_connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "xui_inbound_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("xui_client_id", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("uuid", sa.String(length=100), nullable=True),
        sa.Column("provider_payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["inbound_connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # --- ETL: Migrate Data from Parent to Child tables ---
    op.execute("""
        INSERT INTO xui_panels (server_id, username, password_encrypted, verify_ssl, panel_type, provider_payload, panel_path, subscription_path, subscription_json_path, session_cookies_encrypted, session_created_at, created_at, updated_at)
        SELECT id, username, password_encrypted, COALESCE(verify_ssl, 1), COALESCE(panel_type, 'xui'), provider_payload, panel_path, subscription_path, subscription_json_path, session_cookies_encrypted, session_created_at, created_at, updated_at
        FROM servers
    """)

    op.execute("""
        INSERT INTO xui_inbounds (id, xui_id, settings_json, provider_payload, client_count)
        SELECT id, COALESCE(xui_id, 0), settings_json, provider_payload, COALESCE(client_count, 0)
        FROM inbounds
    """)

    op.execute("""
        INSERT INTO xui_inbound_connections (id, xui_client_id, email, uuid, provider_payload)
        SELECT id, xui_client_id, email, uuid, provider_payload
        FROM inbound_connections
    """)
    # ------------------------------------------------------

    with op.batch_alter_table("inbound_connections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.String(length=50),
                server_default="xui_inbound_connection",
                nullable=False,
            )
        )
        batch_op.drop_column("provider_payload")
        batch_op.drop_column("email")
        batch_op.drop_column("xui_client_id")
        batch_op.drop_column("uuid")

    with op.batch_alter_table("inbounds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type", sa.String(length=50), server_default="xui_inbound", nullable=False)
        )
        batch_op.drop_column("provider_payload")
        batch_op.drop_column("client_count")
        batch_op.drop_column("settings_json")
        batch_op.drop_column("xui_id")

    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.drop_column("provider_payload")
        batch_op.drop_column("panel_type")
        batch_op.drop_column("url")
        batch_op.drop_column("username")
        batch_op.drop_column("session_cookies_encrypted")
        batch_op.drop_column("panel_path")
        batch_op.drop_column("is_active")
        batch_op.drop_column("session_created_at")
        batch_op.drop_column("verify_ssl")
        batch_op.drop_column("subscription_json_path")
        batch_op.drop_column("password_encrypted")
        batch_op.drop_column("subscription_path")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "subscription_path",
                sa.VARCHAR(length=500),
                server_default=sa.text("'/sub'"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("password_encrypted", sa.TEXT(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "subscription_json_path",
                sa.VARCHAR(length=500),
                server_default=sa.text("'/subjson'"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("verify_ssl", sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False)
        )
        batch_op.add_column(sa.Column("session_created_at", sa.DATETIME(), nullable=True))
        batch_op.add_column(
            sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "panel_path", sa.VARCHAR(length=500), server_default=sa.text("'/'"), nullable=True
            )
        )
        batch_op.add_column(sa.Column("session_cookies_encrypted", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("username", sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column("url", sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(
            sa.Column(
                "panel_type", sa.VARCHAR(length=50), server_default=sa.text("'xui'"), nullable=True
            )
        )
        batch_op.add_column(sa.Column("provider_payload", sqlite.JSON(), nullable=True))

    with op.batch_alter_table("inbounds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("xui_id", sa.INTEGER(), server_default=sa.text("0"), nullable=False)
        )
        batch_op.add_column(
            sa.Column("settings_json", sa.TEXT(), server_default=sa.text("'{}'"), nullable=True)
        )
        batch_op.add_column(
            sa.Column("client_count", sa.INTEGER(), server_default=sa.text("0"), nullable=False)
        )
        batch_op.add_column(sa.Column("provider_payload", sqlite.JSON(), nullable=True))
        batch_op.drop_column("type")

    with op.batch_alter_table("inbound_connections", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column("xui_client_id", sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column("email", sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column("provider_payload", sqlite.JSON(), nullable=True))
        batch_op.drop_column("type")

    # --- ETL: Migrate Data from Child to Parent tables ---
    op.execute("""
        UPDATE servers
        SET username = xui_panels.username,
            password_encrypted = xui_panels.password_encrypted,
            verify_ssl = COALESCE(xui_panels.verify_ssl, 1),
            panel_type = COALESCE(xui_panels.panel_type, 'xui'),
            provider_payload = xui_panels.provider_payload,
            panel_path = xui_panels.panel_path,
            subscription_path = xui_panels.subscription_path,
            subscription_json_path = xui_panels.subscription_json_path,
            session_cookies_encrypted = xui_panels.session_cookies_encrypted,
            session_created_at = xui_panels.session_created_at
        FROM xui_panels
        WHERE servers.id = xui_panels.server_id
    """)

    op.execute("""
        UPDATE inbounds
        SET xui_id = COALESCE(xui_inbounds.xui_id, 0),
            settings_json = xui_inbounds.settings_json,
            client_count = COALESCE(xui_inbounds.client_count, 0),
            provider_payload = xui_inbounds.provider_payload
        FROM xui_inbounds
        WHERE inbounds.id = xui_inbounds.id
    """)

    op.execute("""
        UPDATE inbound_connections
        SET xui_client_id = xui_inbound_connections.xui_client_id,
            email = xui_inbound_connections.email,
            uuid = xui_inbound_connections.uuid,
            provider_payload = xui_inbound_connections.provider_payload
        FROM xui_inbound_connections
        WHERE inbound_connections.id = xui_inbound_connections.id
    """)
    # ------------------------------------------------------

    op.drop_table("xui_inbound_connections")
    op.drop_table("mtproxy_inbound_connections")
    op.drop_table("awg_inbound_connections")
    op.drop_table("xui_inbounds")
    op.drop_table("mtproxy_inbounds")
    op.drop_table("awg_inbounds")
    op.drop_table("xui_panels")
    op.drop_table("mtproxy_services")
    op.drop_table("awg_services")
    # ### end Alembic commands ###
