"""Mako template for migration scripts."""

"""Add server monitoring and SSH keys

Revision ID: 65fa810792fd
Revises: 2885c900480d
Create Date: 2026-04-24 17:13:45.058063

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '65fa810792fd'
down_revision = '2885c900480d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ssh_key_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('ssh_key_encrypted')
        batch_op.drop_column('is_online')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
