"""Add template_id to Subscription

Revision ID: 80d3830a3271
Revises: 20260401_1200
Create Date: 2026-04-14 17:05:55.803942

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "80d3830a3271"
down_revision = "20260401_1200"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions") as batch_op:
        batch_op.add_column(sa.Column("template_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_subscriptions_template_id",
            "subscription_templates",
            ["template_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions") as batch_op:
        batch_op.drop_constraint("fk_subscriptions_template_id", type_="foreignkey")
        batch_op.drop_column("template_id")
    # ### end Alembic commands ###
