"""Mako template for migration scripts."""

"""add strict fields to vpn connections

Revision ID: 1ab520fe48a5
Revises: f3d4e9f6a3a0
Create Date: 2026-04-24 23:30:01.379647

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '1ab520fe48a5'
down_revision = 'f3d4e9f6a3a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('awg_inbound_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_ip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('public_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('private_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('psk', sa.String(length=100), nullable=True))

    with op.batch_alter_table('mtproxy_inbound_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mtproxy_inbound_connections', schema=None) as batch_op:
        batch_op.drop_column('secret')

    with op.batch_alter_table('awg_inbound_connections', schema=None) as batch_op:
        batch_op.drop_column('psk')
        batch_op.drop_column('private_key')
        batch_op.drop_column('public_key')
        batch_op.drop_column('client_ip')

    # ### end Alembic commands ###
