"""Mako template for migration scripts."""

"""Add subscription templates support

Revision ID: 227475f1f48c
Revises: 20260326_2000
Create Date: 2026-03-26 16:45:51.350081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227475f1f48c'
down_revision = '20260326_2000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_total_gb', sa.Integer(), nullable=False),
    sa.Column('default_expiry_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_template_inbounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('inbound_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inbound_id'], ['inbounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['subscription_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip column type changes for SQLite - handle manually if needed
    # Skip constraint creation - may already exist
    # Skip column drop - handle manually if needed
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip column and constraint operations for SQLite compatibility
    op.drop_table('subscription_template_inbounds')
    op.drop_table('subscription_templates')
    # ### end Alembic commands ###
