"""Mako template for migration scripts."""

"""add ssh fields to server model

Revision ID: 2885c900480d
Revises: b2144e357853
Create Date: 2026-04-24 16:10:49.058495

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2885c900480d"
down_revision = "b2144e357853"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=200),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=200),
            nullable=False,
        )
        batch_op.create_unique_constraint("uq_clients_email", ["email"])
        batch_op.create_unique_constraint("uq_clients_telegram_username", ["telegram_username"])

    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ssh_port", sa.Integer(), server_default="22", nullable=False)
        )
        batch_op.add_column(
            sa.Column("ssh_user", sa.String(length=100), server_default="root", nullable=False)
        )
        batch_op.add_column(sa.Column("ssh_password_encrypted", sa.Text(), nullable=True))
        batch_op.create_unique_constraint("uq_servers_name", ["name"])

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_subscriptions_token", ["subscription_token"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_constraint("uq_subscriptions_token", type_="unique")

    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.drop_constraint("uq_servers_name", type_="unique")
        batch_op.drop_column("ssh_password_encrypted")
        batch_op.drop_column("ssh_user")
        batch_op.drop_column("ssh_port")

    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_constraint("uq_clients_telegram_username", type_="unique")
        batch_op.drop_constraint("uq_clients_email", type_="unique")
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=100),
            nullable=True,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
