"""Mako template for migration scripts."""

"""Add is_active back to servers

Revision ID: f3d4e9f6a3a0
Revises: 6ef042042a42
Create Date: 2026-04-24 22:04:57.830632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d4e9f6a3a0'
down_revision = '6ef042042a42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
