"""Mako template for migration scripts."""

"""Add provider_payload and panel_type

Revision ID: b2144e357853
Revises: 9aa631a1d506
Create Date: 2026-04-22 12:53:42.420377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2144e357853"
down_revision = "9aa631a1d506"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbound_connections", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provider_payload", sa.JSON(), nullable=True))
        batch_op.alter_column("xui_client_id", existing_type=sa.VARCHAR(length=100), nullable=True)
        batch_op.alter_column("email", existing_type=sa.VARCHAR(length=200), nullable=True)
        batch_op.alter_column("uuid", existing_type=sa.VARCHAR(length=100), nullable=True)

    with op.batch_alter_table("inbounds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provider_payload", sa.JSON(), nullable=True))
        batch_op.alter_column("port", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "settings_json",
            existing_type=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("'{}'"),
        )

    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("panel_type", sa.String(length=50), server_default="xui", nullable=False)
        )
        batch_op.add_column(sa.Column("provider_payload", sa.JSON(), nullable=True))
        batch_op.alter_column(
            "panel_path",
            existing_type=sa.VARCHAR(length=500),
            nullable=True,
            existing_server_default=sa.text("'/'"),
        )
        batch_op.alter_column(
            "subscription_path",
            existing_type=sa.VARCHAR(length=500),
            nullable=True,
            existing_server_default=sa.text("'/sub'"),
        )
        batch_op.alter_column(
            "subscription_json_path",
            existing_type=sa.VARCHAR(length=500),
            nullable=True,
            existing_server_default=sa.text("'/subjson'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.alter_column(
            "subscription_json_path",
            existing_type=sa.VARCHAR(length=500),
            nullable=False,
            existing_server_default=sa.text("'/subjson'"),
        )
        batch_op.alter_column(
            "subscription_path",
            existing_type=sa.VARCHAR(length=500),
            nullable=False,
            existing_server_default=sa.text("'/sub'"),
        )
        batch_op.alter_column(
            "panel_path",
            existing_type=sa.VARCHAR(length=500),
            nullable=False,
            existing_server_default=sa.text("'/'"),
        )
        batch_op.drop_column("provider_payload")
        batch_op.drop_column("panel_type")

    with op.batch_alter_table("inbounds", schema=None) as batch_op:
        batch_op.alter_column(
            "settings_json",
            existing_type=sa.TEXT(),
            nullable=False,
            existing_server_default=sa.text("'{}'"),
        )
        batch_op.alter_column("port", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("provider_payload")

    with op.batch_alter_table("inbound_connections", schema=None) as batch_op:
        batch_op.alter_column("uuid", existing_type=sa.VARCHAR(length=100), nullable=False)
        batch_op.alter_column("email", existing_type=sa.VARCHAR(length=200), nullable=False)
        batch_op.alter_column("xui_client_id", existing_type=sa.VARCHAR(length=100), nullable=False)
        batch_op.drop_column("provider_payload")

    # ### end Alembic commands ###
