"""Add per-connection traffic and expiry limits to inbound_connections

Revision ID: 20260326_2000
Revises: 20260325_2000
Create Date: 2026-03-26 20:00:00.000000
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '20260326_2000'
down_revision = '20260325_2000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_connections', sa.Column('total_gb', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('inbound_connections', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))

    # Populate existing connections with values from their subscriptions
    # This ensures backward compatibility for existing data
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE inbound_connections
        SET
            total_gb = (SELECT total_gb FROM subscriptions WHERE subscriptions.id = inbound_connections.subscription_id),
            expiry_date = (SELECT expiry_date FROM subscriptions WHERE subscriptions.id = inbound_connections.subscription_id)
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_connections', 'expiry_date')
    op.drop_column('inbound_connections', 'total_gb')
    # ### end Alembic commands ###
